export const USER_FIELDS_COUNT = 1

export const CURRENT_POSITION_ICONS_COUNT = 16
export const CURRENT_POSITION_ICONS_SIZE = [56, 56]
export const CURRENT_POSITION_ICONS_OFFSET = [-28, -42]

export const CLUSTER_SPOT_TEXT_LIMIT = 26
